name: Build Docker Image
on:
  push:
    branches:
      - build
  pull_request:
    branches:
      - build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: morestickers-converter:latest
          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Push Docker image to GitHub Container Registry
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: ghcr.io/${{ github.repository }}/morestickers-converter:latest